### ISSUE TITLE
function to:Error: EXDEV: cross-device link not permitted, rename 'C:\Users\user\AppData\Local\Temp\upload_299a073c45135b1429d9b629c66b7fc5.jpg' -> 'e:\nodework\xxxx\bin\public\images\new1472091498447.jpg'

### ISSUE THREAD

**Issue by TimuJiang** [vnykmshr/formidable-upload#2]
function to:Error: EXDEV: cross-device link not permitted, rename 'C:\Users\user\AppData\Local\Temp\upload_299a073c45135b1429d9b629c66b7fc5.jpg' -> 'e:\nodework\xxxx\bin\public\images\new1472091498447.jpg'

**Comment by vnykmshr** [comment]
It looks more like a platform specific issue, you can't rename files across file systems/partitions.

You should try and see if you can configure the upload middleware to use a temporary directory on the same file system as the final location of the files. It works on on platforms that don't create a separate partition for temp files.

Temp dir in your case is on `C:\` while your application code is residing in `E:\`. See if you can update os temp dir to be on E drive or move your application code on C drive.

**Comment by TimuJiang** [comment]
Got it,thanks for your reply

**Comment by vnykmshr** [comment]
You're welcome.
